unepwcmc/cites-compliance-tool

Gemfile
Gemfile.lock
README.md
config/webpacker.yml

* Disables the PG gem to avoid bundler installation issues (we can re-add as appropriate seeing as we don't need it yet)
* Updates the readme with a basic local development process
* Updates webpacker to support hot-reloading

Remove PG gem, update readme and add hot reloading to to webpacker.

---

app/javascript/app.vue
app/javascript/components/IssuesChart.vue

~⚠ Don't merge until https://github.com/unepwcmc/cites-compliance-tool/pull/3 has been accepted and this PR has been changed to point to `develop`~
This add the "Issues reported" chart component.
* Download link doesn't go anywhere
* 2017 edge-case hasn't been resolved yet (no future years)

Issues chart component

---

app/javascript/app.vue
app/javascript/components/IssuesReported.vue

~⚠ Don't merge until https://github.com/unepwcmc/cites-compliance-tool/pull/3 has been accepted and this PR has been changed to point to `develop`~
This add the "Issues currently reported" component.
* Download link doesn't go anywhere

Issues reported component

---

app/javascript/app.vue
app/javascript/components/IssuesCategories.vue
app/javascript/components/IssuesCategoriesChart.vue

~⚠ Don't merge until https://github.com/unepwcmc/cites-compliance-tool/pull/3 has been accepted and this PR has been changed to point to `develop`~
This add the "Issues by category" component.
* Download link doesn't go anywhere
* Maximum values used to calculate doughnut are hard-coded (to 200)
* Will look odd with any more than 3 categories

Issues categories component

---

app/javascript/app.vue

Tiny PR adding logo to navbar
* Rest of navbar currently isn't styled correctly (will be tackled in future PRs)

Add logo to navbar

---

app/javascript/app.vue
app/javascript/components/TopCommodities.vue

This adds the "Top 5 commodity" component.
* Download links don't go anywhere
* Full List button doesn't go anywhere

Top commodities component

---

app/javascript/app.vue
app/javascript/components/IssuesTaxonomies.vue

This adds the "Issues by taxonomy" component.
* Download links don't go anywhere
* Bars currently have a zero-point that starts at 30% of the component height so the labels don't overlap

Issues by taxonomy component

---

app/javascript/app.vue
app/javascript/components/TopSpecies.vue

This adds the "Top 5 species" component.
* Download links don't go anywhere
* Full List button doesn't go anywhere
* Table element will be pulled into a separate component at a later date for use elsewhere

Top species component

---

app/javascript/components/IssuesChart.vue
app/javascript/components/IssuesChartPanel.vue

Moves chart panels to sub-component

Move chart panel to sub-component

---

app/javascript/app.vue
app/javascript/components/IssuesChart.vue
app/javascript/data/chart.js
app/javascript/data/years.js

* Moves year list into a file with the idea that these values will be retrieved dynamically in the future
* Don't display first or last chart panels depending on which year is selected

Move years into dynamic list

---

app/controllers/api/v1/sapi_controller.rb
config/routes.rb
lib/modules/shipments_api_retriever.rb

This is about adding an internal api controller to handle requests to SAPI in order to fetch the shipments.
This includes latest changes that have been made on the `compliance_tool` branch

Internal api

---

app/controllers/api/v1/sapi_controller.rb
app/controllers/download_controller.rb
config/routes.rb
lib/modules/csv_downloader.rb
lib/modules/shipments_api_retriever.rb

Add call methods to retrieve data to be downloaded

Download functionality

---

app/controllers/api/v1/sapi_controller.rb
lib/modules/shipments_api_retriever.rb

This is for adding the `per_page` parameter to the search call permitted parameters

Pagination enhancement

---

app/javascript/DashboardPage.vue
app/javascript/components/IssuesCategories.vue
app/javascript/components/IssuesCategoriesChart.vue
app/javascript/components/IssuesTaxonomies.vue
app/javascript/components/TopCommodities.vue
app/javascript/components/TopCountries.vue
app/javascript/components/TopSpecies.vue
app/javascript/elements/ComponentLinks.vue
app/views/dashboard/index.html.erb

* Adds download links for all components on dashboard
* Download links for taxonomy component don't work

Add download links for dashboard components

---

app/javascript/components/SearchList.vue

* Adds download links for each row in search results
* Download All button above table isn't hooked up yet

Add download links for search page

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/modals.scss
app/javascript/DashboardPage.vue
app/javascript/components/SearchList.vue
app/javascript/components/TopCommodities.vue
app/javascript/components/TopCountries.vue
app/javascript/components/TopSpecies.vue
app/views/dashboard/index.html.erb

* Adds modals for the Full List tables
* Utilises the existing table component for the search page
* Download links won't work on this until other PRs are merged
* Limited to 8 rows otherwise scrollbar made things look pretty bad

Full List table modals

---

app/assets/stylesheets/components/issues-categories.scss
app/assets/stylesheets/modals.scss
app/assets/stylesheets/pages/accounts.scss
app/assets/stylesheets/tables.scss
app/controllers/users_controller.rb
app/javascript/AccountsPage.vue
app/javascript/DashboardPage.vue
app/javascript/SearchPage.vue
app/javascript/components/IssuesCategoriesChart.vue
app/javascript/components/IssuesReported.vue
app/javascript/components/IssuesTaxonomies.vue
app/javascript/components/SearchList.vue
app/javascript/components/TopCommodities.vue
app/javascript/components/TopCountries.vue
app/javascript/components/TopSpecies.vue
app/javascript/elements/ComponentLinks.vue
app/javascript/elements/SiteHeader.vue
app/views/accounts/index.html.erb
app/views/dashboard/index.html.erb
app/views/search/index.html.erb

* Fixes download links in various places
* Link logo to main dashboard page
* Show download icon instead of ellipsis dropdown if no details link
* Hide accounts link for non-admin users
* Allow new users to be assigned the admin role
* None

Various front-end tasks

---

app/javascript/AccountsPage.vue
app/javascript/DashboardPage.vue
app/javascript/SearchPage.vue
app/views/layouts/application.html.erb
package.json
yarn.lock

* Remove Font Awesome packages
* Request Font Awesome using CDN
* Nones

Fix issue with Font Awesome icons not appearing at times

---

app/assets/stylesheets/typography.scss
app/javascript/components/IssuesReported.vue
app/javascript/components/SearchList.vue
app/javascript/components/TopCommodities.vue
app/javascript/components/TopSpecies.vue
app/javascript/elements/ComponentLinks.vue
app/javascript/elements/SiteHeader.vue
app/javascript/helpers/downloader.js
app/javascript/mixins/click-download.js

* Italicises species names
* Renames Top Commodity to Top Commodities
* Downloads are performed using AJAX and `Blob` to avoid reloading the page
* Downloads happen asynchronously now so there's no indication of download progress
* Each download link is disabled if a download for that link is currently in progress

Various feedback fixes

---

app/assets/stylesheets/login.scss
app/assets/stylesheets/modals.scss
app/assets/stylesheets/pages/accounts.scss
app/assets/stylesheets/tables.scss
app/assets/stylesheets/typography.scss
app/javascript/AccountsPage.vue
app/javascript/components/IssuesReported.vue
app/javascript/components/SearchList.vue
app/javascript/components/TopCommodities.vue
app/javascript/components/TopCountries.vue
app/javascript/components/TopSpecies.vue
app/javascript/elements/ComponentLinks.vue
app/javascript/elements/SiteHeader.vue
app/javascript/helpers/downloader.js
app/views/layouts/application.html.erb

⚠ **Relies on https://github.com/unepwcmc/cites-compliance-tool/pull/45 to be merged before this**
* Adds [polyfill.io](http://polyfill.io) dependency to fix various APIs (eg. `Promise`, `Array.includes()`, etc)
* Fixes various styling and layout quirks with IE 11
* Uses `FormData.append()` instead of `FormData.set()` 
* Uses `window.navigator.msSaveOrOpenBlob()` for downloads in IE
* None

Fixes known issues with IE 11 and Edge

---

app/controllers/dashboard_controller.rb
app/javascript/DashboardPage.vue
app/javascript/components/IssuesCategories.vue
app/javascript/components/IssuesChart.vue
app/javascript/components/IssuesReported.vue
app/javascript/components/IssuesTaxonomies.vue
app/javascript/components/TopCommodities.vue
app/javascript/components/TopCountries.vue
app/javascript/components/TopSpecies.vue
app/views/dashboard/index.html.erb

* Adds AJAX loading for all dashboard components
* The taxonomy component is slow to load (the rest are fine)

Load dashboard components using AJAX

---

app/assets/images/icon-arrow-right-end-light.svg
app/assets/stylesheets/icons.scss
app/assets/stylesheets/tables.scss
app/javascript/components/SearchListPagination.vue

⚠ **Waiting on sign-off from Charlotte. Do not merge.**
* Adds buttons to skip to first and last pages on search results
**Waiting on sign-off from Charlotte. Do not merge.**
* None

Add buttons to skip to first and last pages

---

lib/modules/shipments_api_retriever.rb

To be merged together with PR # 686 on SAPI side

Add endpoint for chart data

---

app/assets/stylesheets/tiles.scss
app/javascript/components/IssuesCategories.vue
app/javascript/components/IssuesChart.vue
app/javascript/components/IssuesReported.vue
app/javascript/components/IssuesTaxonomies.vue
app/javascript/components/TopCommodities.vue
app/javascript/components/TopCountries.vue
app/javascript/components/TopSpecies.vue
app/javascript/elements/ComponentLoading.vue

* Adds loading indicators to dashboard components
* None

Add loading indicator for components

---

app/assets/stylesheets/buttons.scss
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb

## Description
- Add title
- Remove lorem ipsum

Add title to login page and remove lorem ipsum

---

.env.example
config/secrets.yml
lib/modules/shipments_api_retriever.rb

In the `.env` you must add the `CERTIFICATE_PATH` value

Add ssl certificate

---

.env.example
config/environments/production.rb
config/environments/staging.rb
config/secrets.yml

* Fix mailer not working on production

Add mailer config options for production
